name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  gradle build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'
    - run: ./gradlew build --no-daemon
